### ISSUE TITLE
Print Issue in Kapre (Normalization2D)

### ISSUE THREAD

**Issue by rtirene** [keunwoochoi/transfer_learning_music#5]
Hi! I'm currently using the feature_extractor model described in keras2_model to iteratively extract features from some audio files. I have an issue with the Normalization2D class of kapre, in particular with the print at row 118:

 if int_axis is not None:
                print('int_axis={} passed but is ignored, str_axis is used instead.'.format(int_axis))

I wanted to ask, it is possible to avoid this print in any way? Thank you in advance for your help 
Best Regards
Tatiana Irene

**Comment by keunwoochoi** [comment]
Hi. Is it critical?

**Comment by rtirene** [comment]
Unfortunately is critical because I have to analyze a huge number of audio files ,and, using Jupyter Notebook, that amount of prints would cause the Notebook execution to crash.

**Comment by keunwoochoi** [comment]
That sounds a bit strange because it is printed only when the layer is initiated. You can try to separate the model creation (or loading) and `predict`.

**Comment by rtirene** [comment]
Actually I just thought about it a minute ago! Thank you so much!

Il giorno ven 15 dic 2017 alle 18:42 Keunwoo Choi <notifications@github.com>
ha scritto:
