### ISSUE TITLE
n_hop size

### ISSUE THREAD

**Issue by svbueno** [keunwoochoi/transfer_learning_music#6]
Hi, I am trying n_hop = 512, but, I get an error during Flatten() 
Could you help me?

**Comment by keunwoochoi** [comment]
Hi, I have no idea what's going on without any more details.

**Comment by keunwoochoi** [comment]
But if you're having error in Flatten() probably you wanna have check out the input shape.

**Comment by svbueno** [comment]
The input shape, Indeed. If I change n_hop to 512, I will have half the input size, because stft will not overlap. So I need to add a layer of upsampling or change the pooling. I think I got it now, thank you.
